#! /bin/sh

panel &
caffeine &

bspc config border_width         0
bspc config window_gap           15
bspc config top_padding          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc config presel_feedback_color '#6f5990'

bspc monitor -d Web Code Term Misc
