#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'C%a %b %-d' > "$PANEL_FIFO" &
clock -sf 'S%-I:%M %p' > "$PANEL_FIFO" &
essid -s -i 1 -f 'E%s' -w wlp1s0 > "$PANEL_FIFO" &
while true; do acpi -b | grep -Eo "[0-9]+%" | sed -e 's/^/B/' | sed -e 's/.$//'; sleep 1; done > "$PANEL_FIFO" &
while true; do echo "100 *" $(iwconfig | grep -Eo "Link Quality=([0-9]+/[0-9]+)" | grep -Eo "[0-9]+/[0-9]+") | bc | sed -e 's/^/F/'; sleep 1; done > "$PANEL_FIFO" &
while true; do free | grep -Eo "Mem:(\s)*[0-9]+(\s)+[0-9]+" | grep -Eo "[0-9]+(\s)+[0-9]+" | sed -e "s/\s\+/ * /" | sed -e "s/^/100 \/ /" | bc -l | sed -e "s/$/ \/ 1/" | bc | sed -e 's/^/R/'; sleep 1; done > "$PANEL_FIFO" &
while true; do  mpc | head -n 1 | grep -Eo "\- (.*)" | cut -c 3- | sed -e 's/^/M/'; sleep 1; done > "$PANEL_FIFO" &
# ip link | grep -m 1 link/ether | grep -Eo ([0-9a-f]{2}:){5}[0-9a-f]{2} | head -n 1

. panel_vars

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$FONT_FONT","$ICON_FONT" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" | while read line; do eval "$line"; done &

wait
