#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_vars

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
  case $line in
    S*)
      # clock output
      clock="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
      clock="%{F$COLOR_ICON}${ICON_CLOCK}%{F-}${clock}"
      ;;
    C*)
      # calendar output
      cal="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
      cal="%{F$COLOR_ICON}${ICON_CAL}%{F-}${cal}"
      ;;
    E*)
      # ssid output
      wifi="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
      wifi="${wificon}${wifi}"
      ;;
    F*)
      # wifi signal
      if ((${line#?} > 90))
      then
        wificon="%{F$COLOR_ICON}${ICON_WIFI}%{F-}"
      else
        if ((${line#?} > 80))
        then
          wificon="%{F$COLOR_WARN}${ICON_WIFI}%{F-}"
        else
          wificon="%{F$COLOR_ERR}${ICON_WIFI}%{F-}"
        fi
      fi
      ;;
    B*)
      # battery output
      if ((${line#?} > 50))
        then
        battcon="%{F$COLOR_ICON}${ICON_PWR}%{F-}"
      else
        if ((${line#?} > 20))
          then
          battcon="%{F$COLOR_WARN}${ICON_PWR}%{F-}"
        else
          battcon="%{F$COLOR_ERR}${ICON_PWR}%{F-}"
        fi
      fi
      batt="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?}% %{B-}%{F-}"
      batt="${battcon}${batt}"
      ;;
    R*)
      # ram stats
      if ((${line#?} < 25))
        then
        ramcon="%{F$COLOR_ICON}${ICON_DB}%{F-}"
      else
        if ((${line#?} > 70))
          then
          ramcon="%{F$COLOR_WARN}${ICON_DB}%{F-}"
        else
          ramcon="%{F$COLOR_ERR}${ICON_DB}%{F-}"
        fi
      fi
      ram="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?}% %{B-}%{F-}"
      ram="${ramcon}${ram}"
      ;;
    T*)
      # xtitle output
      title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
      ;;
    M*)
      #Music
      music="%{F$COLOR_ICON} %{A:mpc next:}<<%{A} %{A:mpc toggle:}${line#?}%{A} %{A:mpc prev:}>>%{A} %{F-}"
      ;;
    W*)
      # bspwm internal state
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          M*)
            # active monitor
            if [ $num_mon -gt 1 ] ; then
              wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
            fi
            ;;
          m*)
            # inactive monitor
            if [ $num_mon -gt 1 ] ; then
              wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
            fi
            ;;
          O*)
            # focused occupied desktop
            wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOCUSED_OCCUPIED_UL}%{+u} ${name} %{-u}%{B-}%{F-}"
            ;;
          F*)
            # focused free desktop
            wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOCUSED_FREE_UL}%{+u} ${name} %{-u}%{B-}%{F-}"
            ;;
          U*)
            # focused urgent desktop
            wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
            ;;
          o*)
            # occupied desktop
            wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}%{U$COLOR_OCCUPIED_UL}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{-u}%{B-}%{F-}"
            ;;
          f*)
            # free desktop
            wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
            ;;
          u*)
            # urgent desktop
            wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
            ;;
          L*)
            # layout
            wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
            ;;
        esac
        shift
      done
      ;;
  esac
  printf "%s\n" "%{l}${wm_infos}${music}%{c}${title}%{r}${ram}// ${batt}// ${wifi}// ${cal}// ${clock}"
done
